### ISSUE TITLE
pixloc

### ISSUE THREAD

**Issue by joaquinsalas** [benjaminkelenyi/SAM-Net#2]
Hi, thanks for sharing your code. 

I am trying to run test.py, but it looks like pixloc is a folder without files. Would you please help me to confirm this? Thanks

**Comment by benjaminkelenyi** [comment]
Yes, as you can see, the 'pixloc' folder is a submodule. We utilized the inference part from 'pixloc' in our model. You can download it from the original GitHub repository: https://github.com/cvg/pixloc or from our Google Drive repository: https://drive.google.com/drive/folders/1SyWAScRUpcC32LSTZcku16ZHMfMctymR.
